apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-apps
  namespace: argocd
spec:
  description: >
    The application layer for SPOKE clusters

  sourceRepos:
    - "https://github.com/trandinhphuoc1198/argocd-eks.git"

  destinations:
    - server: "*"
      namespace: fastapi
    - server: "*"
      namespace: db

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace          # CreateNamespace=true on both ApplicationSets

  namespaceResourceWhitelist:
    - group: ""
      kind: Service
    - group: ""
      kind: Secret
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: ConfigMap
    - group: apps
      kind: Deployment
    - group: keda.sh
      kind: ScaledObject
    - group: monitoring.coreos.com
      kind: ServiceMonitor
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
    - group: postgresql.cnpg.io
      kind: Cluster
    - group: postgresql.cnpg.io
      kind: Pooler