apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "50"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-hub-observability
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: loki
      targetRevision: "12.0.0"
      helm:
        releaseName: loki
        valueFiles:
          - $values/platform/values/hub/loki.yaml
    - repoURL: https://github.com/trandinhphuoc1198/argocd-eks.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/trandinhphuoc1198/argocd-eks.git
      targetRevision: main
      path: platform/webhook-guards
      directory:
        include: "wait-for-pod-identity-webhook.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
